# Generated by Django 2.2 on 2020-12-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
