# Generated by Django 2.2 on 2020-12-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_auto_20201204_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
